version: "3"

services:
    web:
        build:
          context: .
          dockerfile: ./compose/web/Dockerfile
        image: ls-auth-api_web
        expose:
          - "5000"
        ports:
          - "5000:5000"
        volumes:
          - "./:/app/app"
        env_file: .env
        working_dir: /app/app
        command: ./start.sh
        links:
          - database

    database:
        image: postgres:12
        volumes:
          - lsdb_data:/var/lib/postgresql
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
        expose:
          - "5432"
        ports:
          - "5432:5432"


    blockchain:
      build:
        context: .
        dockerfile: ./compose/blockchain/Dockerfile
      image: ls-auth-api_blockchain
      expose:
        - "8080"
      ports:
        - "8080:8080"

volumes:
    lsdb_data:
        driver: local
