"""Add blockchain details to DIDs and credentials

Revision ID: 32f3dfe29b35
Revises: cac1760abd95
Create Date: 2022-05-17 20:32:39.244012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32f3dfe29b35"
down_revision = "cac1760abd95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("DID", sa.Column("creation_date", sa.DateTime(), nullable=True))
    op.add_column("DID", sa.Column("submission_date", sa.DateTime(), nullable=True))
    op.add_column(
        "DID", sa.Column("submission_transaction_id", sa.Text(), nullable=True)
    )
    op.add_column("DID", sa.Column("last_check_date", sa.DateTime(), nullable=True))
    op.add_column(
        "credential", sa.Column("signed_credential_hash", sa.Text(), nullable=True)
    )
    op.add_column("credential", sa.Column("batch_id", sa.Text(), nullable=True))
    op.add_column(
        "credential", sa.Column("creation_operation_hash", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("creation_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("submission_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("submission_transaction_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("revocation_operation_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("revocation_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("revocation_transaction_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("last_check_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credential", "last_check_date")
    op.drop_column("credential", "revocation_transaction_id")
    op.drop_column("credential", "revocation_date")
    op.drop_column("credential", "revocation_operation_id")
    op.drop_column("credential", "submission_transaction_id")
    op.drop_column("credential", "submission_date")
    op.drop_column("credential", "creation_date")
    op.drop_column("credential", "creation_operation_hash")
    op.drop_column("credential", "batch_id")
    op.drop_column("credential", "signed_credential_hash")
    op.drop_column("DID", "last_check_date")
    op.drop_column("DID", "submission_transaction_id")
    op.drop_column("DID", "submission_date")
    op.drop_column("DID", "creation_date")
    # ### end Alembic commands ###
