"""empty message

Revision ID: 4a0e2c16ba08
Revises: ea4def203854
Create Date: 2022-01-23 20:19:51.446291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4a0e2c16ba08"
down_revision = "ea4def203854"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credential", sa.Column("holder", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.drop_column("credential", "issuer")
    op.add_column(
        "credential", sa.Column("issuer", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_unique_constraint(None, "credential", ["id"])
    op.create_foreign_key(None, "credential", "user", ["holder"], ["id"])
    op.create_foreign_key(None, "credential", "user", ["issuer"], ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.drop_constraint(None, "credential", type_="unique")
    op.drop_column("credential", "holder")
    # ### end Alembic commands ###
