"""empty message

Revision ID: 62404ecfa3eb
Revises: fd3ab942b223
Create Date: 2022-04-18 11:04:17.084530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62404ecfa3eb"
down_revision = "fd3ab942b223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("DID", sa.Column("seed", sa.Text(), nullable=True))
    op.add_column("DID", sa.Column("passphrase", sa.Text(), nullable=True))
    op.add_column("DID", sa.Column("did_long_form", sa.Text(), nullable=True))
    op.add_column("DID", sa.Column("creation_operation_id", sa.Text(), nullable=True))
    op.add_column("DID", sa.Column("state_hash", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "DID", ["id"])
    op.create_unique_constraint(None, "presentation", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "presentation", type_="unique")
    op.drop_constraint(None, "DID", type_="unique")
    op.drop_column("DID", "state_hash")
    op.drop_column("DID", "creation_operation_id")
    op.drop_column("DID", "did_long_form")
    op.drop_column("DID", "passphrase")
    op.drop_column("DID", "seed")
    # ### end Alembic commands ###
