"""empty message

Revision ID: cac1760abd95
Revises: 62404ecfa3eb
Create Date: 2022-05-02 12:23:19.104841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cac1760abd95"
down_revision = "62404ecfa3eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("DID", sa.Column("mnemonic", sa.Text(), nullable=True))
    op.drop_column("DID", "seed")
    op.add_column(
        "credential", sa.Column("signed_credential_content", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("signed_credential_canonical", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("signed_credential_proof", sa.Text(), nullable=True)
    )
    op.add_column(
        "credential", sa.Column("creation_operation_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credential", "creation_operation_id")
    op.drop_column("credential", "signed_credential_proof")
    op.drop_column("credential", "signed_credential_canonical")
    op.drop_column("credential", "signed_credential_content")
    op.add_column(
        "DID", sa.Column("seed", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("DID", "mnemonic")
    # ### end Alembic commands ###
