"""Add DID table

Revision ID: e9e00a2b393d
Revises: 2ce32f72586a
Create Date: 2022-03-14 20:28:35.724963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e9e00a2b393d"
down_revision = "2ce32f72586a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DID",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("DID", sa.Text(), nullable=True),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("primary", sa.Boolean(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "skill", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "skill", type_="unique")
    op.drop_table("DID")
    # ### end Alembic commands ###
